#######################################################
##  Platform Gigaset Elements, adds sensor and arming switches
#######################################################

gigasetelements:
    # Name for components
    name: "gigasetelements alarm"
    # Username - your username to Gigaset Elements
    username: !secret gigasetelements_username
    # Password - your password to Gigaset Elements
    password: !secret gigasetelements_password
    # Switches - create switches for armed_away, armed_home and armed_night
    switches: True
