#######################################################
##  Platform Gigaset Elements, adds sensor and arming switches
#######################################################

gigasetelements:
    # Name for components
    name: "gigasetelements alarm"
    # Username - your username to Gigaset Elements
    username: !secret gigasetelements_username
    # Password - your password to Gigaset Elements
    password: !secret gigasetelements_password
    # Switches - create switches for armed_away, armed_home and armed_night
    switches: True
    # Code - Code to enable or disable the alarm in the frontend
    code: 1234
    # Code_arm_required - require code for armed_away, armed_home and armed_night
    code_arm_required: True
